###
GET http://localhost:3000/


###
GET http://localhost:3000/transaction


###
POST http://localhost:3000/api/v1/transaction
Content-Type: application/json

{
    "value" : "100000",
    "payerId" : "fb3399b7-cc9c-4265-89fc-57a299995849",
    "payeeId" : "f46b0ee5-cd76-4267-bf71-cd50ec0d78a7"
}

###
POST http://localhost:3000/api/v1/transaction
Content-Type: application/json

{
    "value" : "500000",
    "payerId" : "fb3399b7-cc9c-4265-89fc-57a299995849",
    "payeeId" : "f46b0ee5-cd76-4267-bf71-cd50ec0d78a7",
    "sleep": 1000
}


### VALIDATE TRANSACTION
GET https://run.mocky.io/v3/69efe5ad-5221-40dd-a11f-3b24e64fbcb8
Content-Type: application/json


### SEND MAILER
POST https://run.mocky.io/v3/0f35cc7d-833a-410c-ba07-7a0500fb9a2b
Content-Type: application/json

{
    "email": "email@email.com"
}